var defaultItemGrid = [
    [

        "Bow",
        "Fire",
        "Ice",
        "Light",
        "Roomkey",
        "Moonstear",
    ],
    [
        "Bombs",
        "Bombchus",
        "stick",
        "Beans",
        "Letter",
        "LandDeed",
        ],
    [
        "PowderKeg",
        "Pictobox",
        "Lens",
        "Hookshot",
        "Pendant",
        "SwampDeed",
    ],
    [
        "DekuPrincess",
        "GoldDust",
        "Bottle",
        "GFsword",
        "ExpressMail",
        "MountainDeed",
    ],
    [
        "Ocarina",
        "Sword",
        "shield",
        "Magic",
        "Wallet",
        "OceanDeed",
    ],
    [
        "SongofTime",
        "Healing",
        "EponasSong",
        "Soaring",
        "SongofStorms",
    ],
    [
        "Sonata",
        "Lullaby",
        "NewWave",
        "Elegy",
        "Oath",
    ],
    [
        "Postman",
        "Allnight",
        "Blast",
        "Stone",
        "GFMask",
        "Deku",
    ],
    [
        "Keaton",
        "Bremen",
        "Bunny",
        "DonGero",
        "Scents",
        "Goron",
    ],
    [
        "Romani",
        "Circus",
        "Kafei",
        "Couple",
        "Truth",
        "Zora",
    ],
    [
        "Kamaro",
        "Gibdo",
        "Garo",
        "Captain",
        "Giant",
        "FD",
    ],
        [
        "Odolwa",
        "Goht",
        "Gyorg",
        "Twinmold",
    ],
 
]


var baseItems = {
    Bow: 0,
    Ocarina: false,
    Hookshot: false,
    Hammer: false,
    stick: false,
    Pictobox: false,
    GFsword: false,
    nut: false,
    Bombs: 0,
    PowderKeg: false,
    Bombchus: false,
    Lens: false,
    Fire: false,
    Ice: false,
    Light: false,
    Bottle: 0,
    Wallet: 0,
    DekuPrincess: false,
    GoldDust: false,
    
    Moonstear: false,
    Roomkey: false,
    Letter: false,
    LandDeed: false,
    SwampDeed: false,
    MountainDeed: false,
    OceanDeed: false,
    Pendant: false,
    ExpressMail: false,

    Sword: 0,
    shield: 0,
    Magic: 0,    
    Beans: false,

    EponasSong: false,
    Healing: false,
    Soaring: false,
    SongofTime: false,
    SongofStorms: false,
    Sonata: false,    
    Lullaby: false,
    NewWave: false,
    Oath: false,
    Elegy: false,
    
    Deku: false,
    Goron: false,
    Zora: false,
    FD: false,
    
    Postman: false,
    Allnight: false,
    Blast: false,
    Stone: false,
    GFMask: false,
    Keaton: false,
    Bremen: false,
    Bunny: false,
    DonGero: false,
    Scents: false,
    Romani: false,
    Circus: false,
    Kafei: false,
    Couple: false,
    Truth: false,
    Kamaro: false,
    Gibdo: false,
    Garo: false,
    Captain: false,
    Giant: false,

    Odolwa: false,
    Goht: false,
    Gyorg: false,
    Twinmold: false,

    blank: false,
};

var itemsMin = {
    Bow: 0,
    Sword: 0,
    shield: 0,
    Bombs: 0,
    Bottle: 0,
    Magic: 0,
    Wallet: 0,
};

var itemsMax = {
    Bow: 3,
    Sword: 3,
    shield: 2,
    Bombs: 3,
    Bottle: 6,
    Magic: 2,
    Wallet: 2,
};

var items = Object.assign(baseItems);
